testthat::test_that("exported API surface is locked", {
  exports <- sort(getNamespaceExports("ledgr"))

  expected <- sort(c(
    "iso_utc",
    "ledgr_adapter_csv",
    "ledgr_adapter_r",
    "ledgr_backtest",
    "ledgr_backtest_bench",
    "ledgr_backtest_run",
    "ledgr_clear_feature_cache",
    "ledgr_compare_runs",
    "ledgr_compute_equity_curve",
    "ledgr_compute_metrics",
    "ledgr_create_schema",
    "ledgr_data_hash",
    "ledgr_db_init",
    "ledgr_deregister_indicator",
    "ledgr_experiment",
    "ledgr_extract_strategy",
    "ledgr_extract_fills",
    "ledgr_feature_id",
    "ledgr_get_indicator",
    "ledgr_ind_ema",
    "ledgr_ind_returns",
    "ledgr_ind_rsi",
    "ledgr_ind_sma",
    "ledgr_ind_ttr",
    "ledgr_indicator",
    "ledgr_indicator_dev",
    "ledgr_list_indicators",
    "ledgr_opening",
    "ledgr_opening_from_broker",
    "ledgr_param_grid",
    "ledgr_pulse_snapshot",
    "ledgr_register_indicator",
    "ledgr_results",
    "ledgr_run",
    "ledgr_run_archive",
    "ledgr_run_info",
    "ledgr_run_label",
    "ledgr_run_list",
    "ledgr_run_open",
    "ledgr_run_tag",
    "ledgr_run_tags",
    "ledgr_run_untag",
    "ledgr_signal_strategy",
    "ledgr_sim_bars",
    "ledgr_snapshot_close",
    "ledgr_snapshot_create",
    "ledgr_snapshot_from_csv",
    "ledgr_snapshot_from_df",
    "ledgr_snapshot_from_yahoo",
    "ledgr_snapshot_import_bars_csv",
    "ledgr_snapshot_import_instruments_csv",
    "ledgr_snapshot_info",
    "ledgr_snapshot_list",
    "ledgr_snapshot_load",
    "ledgr_snapshot_seal",
    "ledgr_state_reconstruct",
    "ledgr_ttr_warmup_rules",
    "ledgr_utc",
    "ledgr_validate_schema"
  ))

  testthat::expect_identical(exports, expected)
  testthat::expect_false("ledgr_snapshot_hash" %in% exports)
})

