testthat::test_that("exported API surface is locked", {
  exports <- sort(getNamespaceExports("ledgr"))

  expected <- sort(c(
    "ledgr_iso_utc",
    "ledgr_adapter_csv",
    "ledgr_adapter_r",
    "ledgr_backtest",
    "ledgr_backtest_bench",
    "ledgr_calendar",
    "ledgr_calendar_crypto",
    "ledgr_calendar_us_equity",
    "ledgr_candidate",
    "ledgr_candidate_reproduction_key",
    "ledgr_feature_cache_clear",
    "ledgr_run_compare",
    "ledgr_compute_metrics",
    "ledgr_cost_chain",
    "ledgr_cost_describe",
    "ledgr_cost_fixed_fee",
    "ledgr_cost_notional_bps_fee",
    "ledgr_cost_spread_bps",
    "ledgr_cost_steps",
    "ledgr_cost_zero",
    "ledgr_db_init",
    "ledgr_indicator_remove",
    "ledgr_demo_sma_crossover_strategy",
    "ledgr_experiment",
    "ledgr_run_strategy",
    "ledgr_run_fills",
    "ledgr_feature_contract_check",
    "ledgr_feature_contracts",
    "ledgr_feature_grid",
    "ledgr_feature_id",
    "ledgr_feature_map",
    "ledgr_fold",
    "ledgr_folds_anchored",
    "ledgr_folds_rolling",
    "ledgr_indicator_get",
    "ledgr_grid_add_baseline",
    "ledgr_grid_cross",
    "ledgr_grid_named",
    "ledgr_ind_ema",
    "ledgr_ind_returns",
    "ledgr_ind_rsi",
    "ledgr_ind_sma",
    "ledgr_ind_ttr",
    "ledgr_ind_ttr_outputs",
    "ledgr_indicator",
    "ledgr_indicator_dev",
    "ledgr_indicator_list",
    "ledgr_metric_context",
    "ledgr_metric_context_hash",
    "ledgr_metric_crypto",
    "ledgr_metric_us_equity",
    "ledgr_opening",
    "ledgr_opening_from_broker",
    "ledgr_param",
    "ledgr_param_grid",
    "ledgr_parameters",
    "ledgr_precompute_features",
    "ledgr_promote",
    "ledgr_promotion_context",
    "ledgr_pulse_features",
    "ledgr_pulse_snapshot",
    "ledgr_pulse_wide",
    "ledgr_indicator_register",
    "ledgr_results",
    "ledgr_risk_chain",
    "ledgr_risk_free_rate",
    "ledgr_risk_long_only",
    "ledgr_risk_max_weight",
    "ledgr_risk_none",
    "ledgr_run",
    "ledgr_sweep",
    "ledgr_run_archive",
    "ledgr_run_info",
    "ledgr_run_label",
    "ledgr_run_list",
    "ledgr_run_open",
    "ledgr_run_promotion_context",
    "ledgr_run_tag",
    "ledgr_run_tags",
    "ledgr_run_untag",
    "ledgr_select_argmax",
    "ledgr_select_argmin",
    "ledgr_selection",
    "ledgr_signal",
    "ledgr_signal_strategy",
    "ledgr_sim_bars",
    "ledgr_snapshot_close",
    "ledgr_snapshot_create",
    "ledgr_snapshot_from_csv",
    "ledgr_snapshot_from_df",
    "ledgr_snapshot_from_yahoo",
    "ledgr_snapshot_import_bars_csv",
    "ledgr_snapshot_import_instruments_csv",
    "ledgr_snapshot_info",
    "ledgr_snapshot_list",
    "ledgr_snapshot_open",
    "ledgr_snapshot_seal",
    "ledgr_state_reconstruct",
    "ledgr_strategy_preflight",
    "ledgr_strategy_grid",
    "ledgr_sweep_retention",
    "ledgr_sweep_info",
    "ledgr_sweep_list",
    "ledgr_sweep_open",
    "ledgr_sweep_pbo",
    "ledgr_sweep_returns",
    "ledgr_sweep_returns_data_frame",
    "ledgr_sweep_returns_matrix",
    "ledgr_sweep_returns_panel",
    "ledgr_sweep_returns_wide",
    "ledgr_sweep_returns_xts",
    "ledgr_sweep_review",
    "ledgr_sweep_save",
    "ledgr_target",
    "ledgr_timing_next_open",
    "ledgr_temp_store",
    "ledgr_ind_ttr_warmup_rules",
    "ledgr_utc",
    "ledgr_validate_schema",
    "ledgr_walk_forward",
    "ledgr_walk_forward_folds",
    "ledgr_walk_forward_open",
    "ledgr_walk_forward_scores",
    "ledgr_weights",
    "ledgr_passed_warmup",
    "ledgr_select_top_n",
    "ledgr_signal_return",
    "ledgr_target_rebalance",
    "ledgr_weight_equal"
  ))

  testthat::expect_identical(exports, expected)
  testthat::expect_false("ledgr_snapshot_hash" %in% exports)
  testthat::expect_false("ledgr_run_fold" %in% exports)
  testthat::expect_false("ledgr_next_open_fill_proposal" %in% exports)
  testthat::expect_false("ledgr_resolve_fill_proposal" %in% exports)
  testthat::expect_false("ledgr_fill_context" %in% exports)
  testthat::expect_false("ledgr_execute_fold" %in% exports)
  testthat::expect_false("ledgr_execution_spec" %in% exports)
  testthat::expect_false("ledgr_memory_output_handler" %in% exports)
  testthat::expect_false("ledgr_backtest_run" %in% exports)
  testthat::expect_false("ledgr_compute_equity_curve" %in% exports)
  testthat::expect_false("ledgr_create_schema" %in% exports)
  testthat::expect_false("ledgr_metric_context_resolve" %in% exports)
  testthat::expect_false(paste0("ledgr_walk_forward_", "extract_candidate") %in% exports)
  testthat::expect_true(exists("ledgr_run_fold", envir = asNamespace("ledgr"), inherits = FALSE))
  testthat::expect_true(exists("ledgr_execute_fold", envir = asNamespace("ledgr"), inherits = FALSE))
  testthat::expect_true(exists("ledgr_execution_spec", envir = asNamespace("ledgr"), inherits = FALSE))
  testthat::expect_true(exists("ledgr_snapshot_connection", envir = asNamespace("ledgr"), inherits = FALSE))
  testthat::expect_identical(names(formals(get("ledgr_snapshot_open", envir = asNamespace("ledgr")))[1]), "db_path")
})

