# Checker for the segmented-feature-views spike.
#
# Spike protocol section 6. Three jobs:
#   1. rerun the runner and the ablation into a scratch directory;
#   2. diff the fresh evidence against the committed CSVs;
#   3. guard package scope, so the spike changed no package file.
#
# Exit status is non-zero on any failure, so this is usable as a gate.
#
# Two defects found in adversarial review 2026-09-27 and fixed here. The scope
# guard read only working-tree status, so a package edit that had been committed
# passed it; it now checks the committed diff against a base as well. And the
# cpp11 revert ran unconditionally, which would have discarded a pre-existing edit
# to those two files; it now runs only if they were clean before the rerun.
#
#   Rscript dev/spikes/segmented-feature-views/spike_checker.R
#   SPIKE_BASE=<ref> Rscript ... # to name a different base for the committed diff

OUT <- "dev/spikes/segmented-feature-views"
GUARDED <- c("R", "src", "tests", "NAMESPACE", "DESCRIPTION", "man", "inst/design")
# Regenerated by pkgload::load_all() on every load, by line endings alone.
LOAD_ARTIFACTS <- c("R/cpp11.R", "src/cpp11.cpp")
BASE <- Sys.getenv("SPIKE_BASE", "origin/v0.2.0.2")
PARTS <- list(
  list(script = "spike_runner.R", csv = "spike_evidence.csv"),
  list(script = "spike_ablation.R", csv = "spike_ablation_evidence.csv")
)

fail <- character()
note <- function(...) cat(..., "\n", sep = "")
git <- function(args) {
  out <- suppressWarnings(system2("git", args, stdout = TRUE, stderr = FALSE))
  if (!is.null(attr(out, "status")) && !identical(as.integer(attr(out, "status")), 0L)) {
    return(NULL)
  }
  out[nzchar(out)]
}

# ------------------------------------------------------- 3. package scope
# Checked first: a spike that edited the package invalidates its own evidence.
# Committing such an edit must not launder it, so both views are checked.
dirty <- git(c("status", "--porcelain", "--", GUARDED))
if (length(dirty) > 0L) {
  fail <- c(fail, "package scope is dirty in the working tree")
  note("FAIL  package scope touched, uncommitted:")
  for (d in dirty) note("        ", d)
} else {
  note("ok    package scope clean in the working tree")
}

base_sha <- git(c("merge-base", "HEAD", BASE))
if (length(base_sha) != 1L) {
  fail <- c(fail, paste0("committed-diff check could not resolve base '", BASE, "'"))
  note("FAIL  cannot resolve base '", BASE, "'; committed package edits NOT checked.")
  note("        Pass SPIKE_BASE=<ref> naming a reachable base.")
} else {
  committed <- git(c("diff", "--name-only", paste0(base_sha, "..HEAD"), "--", GUARDED))
  if (length(committed) > 0L) {
    fail <- c(fail, "package scope changed in commits")
    note("FAIL  package scope touched, committed since ", substr(base_sha, 1, 7), ":")
    for (d in committed) note("        ", d)
  } else {
    note("ok    package scope unchanged in commits since ", substr(base_sha, 1, 7))
  }
}

# The rerun loads the package, which rewrites the cpp11 registration. Reverting
# that is only safe if the author had no edit of their own there.
pre_artifact_state <- git(c("status", "--porcelain", "--", LOAD_ARTIFACTS))
revert_is_safe <- length(pre_artifact_state) == 0L
if (!revert_is_safe) {
  note("note  ", paste(LOAD_ARTIFACTS, collapse = " and "), " already modified;")
  note("        the post-rerun revert is SKIPPED so nothing of yours is discarded.")
}

scratch <- file.path(tempdir(), paste0("spike-scratch-", Sys.getpid()))
dir.create(scratch, recursive = TRUE, showWarnings = FALSE)
on.exit(unlink(scratch, recursive = TRUE), add = TRUE)

for (part in PARTS) {
  recorded_path <- file.path(OUT, part$csv)
  note("")
  note("--- ", part$script)

  # --------------------------------------------------------- 1. rerun fresh
  if (!file.exists(recorded_path)) {
    fail <- c(fail, paste("no recorded evidence for", part$script))
    note("FAIL  no recorded evidence at ", recorded_path)
    next
  }
  recorded <- utils::read.csv(recorded_path, stringsAsFactors = FALSE)

  keep <- tempfile(fileext = ".csv")
  invisible(file.copy(recorded_path, keep, overwrite = TRUE))
  status <- system2(
    file.path(R.home("bin"), "Rscript"),
    file.path(OUT, part$script),
    stdout = file.path(scratch, paste0(part$script, ".log")),
    stderr = file.path(scratch, paste0(part$script, ".err"))
  )
  fresh <- utils::read.csv(recorded_path, stringsAsFactors = FALSE)
  invisible(file.copy(keep, recorded_path, overwrite = TRUE))  # restore committed
  if (revert_is_safe) {
    invisible(system2("git", c("checkout", "--", LOAD_ARTIFACTS)))
  }
  if (!identical(as.integer(status), 0L)) {
    fail <- c(fail, paste(part$script, "exited non-zero"))
    note("FAIL  exit status ", status)
    next
  }
  note("ok    reran to completion")

  # ------------------------------------------------------------- 2. diff
  key <- function(d) paste(d$case, d$key, sep = "\u001f")
  r <- recorded[order(key(recorded)), , drop = FALSE]
  f <- fresh[order(key(fresh)), , drop = FALSE]

  missing <- setdiff(key(r), key(f))
  added <- setdiff(key(f), key(r))
  if (length(missing) > 0L || length(added) > 0L) {
    fail <- c(fail, "evidence row set changed")
    for (m in missing) note("FAIL  row missing on rerun: ", sub("\u001f", " / ", m))
    for (a in added) note("FAIL  row new on rerun:     ", sub("\u001f", " / ", a))
  } else {
    note("ok    evidence row set identical (", nrow(r), " rows)")
  }

  both <- intersect(key(r), key(f))
  rv <- setNames(r$value, key(r))[both]
  fv <- setNames(f$value, key(f))[both]
  drift <- both[rv != fv]
  if (length(drift) > 0L) {
    fail <- c(fail, "evidence values drifted")
    for (d in drift) {
      note("FAIL  ", sub("\u001f", " / ", d), ": recorded ", rv[[d]], " -> fresh ", fv[[d]])
    }
  } else {
    note("ok    all ", length(both), " values reproduce")
  }
}

# ------------------------------------------------------------------ verdict
note("")
if (length(fail) > 0L) {
  note("CHECKER FAILED: ", paste(unique(fail), collapse = "; "))
  quit(status = 1L)
}
note("CHECKER PASSED")
