// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// spot_fifo.cpp
SEXP ledgr_cpp_spot_fifo_batch(SEXP run_id_sxp, SEXP fill_inst_idx_sxp, SEXP fill_instrument_id_sxp, SEXP fill_side_sxp, SEXP fill_qty_sxp, SEXP fill_price_sxp, SEXP fill_fee_sxp, SEXP fill_ts_utc_sxp, SEXP event_seq_start_sxp, SEXP positions_sxp, SEXP cash_sxp, SEXP lot_inst_idx_sxp, SEXP lot_qty_sxp, SEXP lot_price_sxp, SEXP cost_basis_by_inst_sxp, SEXP total_cost_basis_sxp, SEXP realized_pnl_sxp, SEXP realized_comp_sxp);
extern "C" SEXP _ledgr_ledgr_cpp_spot_fifo_batch(SEXP run_id_sxp, SEXP fill_inst_idx_sxp, SEXP fill_instrument_id_sxp, SEXP fill_side_sxp, SEXP fill_qty_sxp, SEXP fill_price_sxp, SEXP fill_fee_sxp, SEXP fill_ts_utc_sxp, SEXP event_seq_start_sxp, SEXP positions_sxp, SEXP cash_sxp, SEXP lot_inst_idx_sxp, SEXP lot_qty_sxp, SEXP lot_price_sxp, SEXP cost_basis_by_inst_sxp, SEXP total_cost_basis_sxp, SEXP realized_pnl_sxp, SEXP realized_comp_sxp) {
  BEGIN_CPP11
    return cpp11::as_sexp(ledgr_cpp_spot_fifo_batch(cpp11::as_cpp<cpp11::decay_t<SEXP>>(run_id_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(fill_inst_idx_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(fill_instrument_id_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(fill_side_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(fill_qty_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(fill_price_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(fill_fee_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(fill_ts_utc_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(event_seq_start_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(positions_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(cash_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(lot_inst_idx_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(lot_qty_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(lot_price_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(cost_basis_by_inst_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(total_cost_basis_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(realized_pnl_sxp), cpp11::as_cpp<cpp11::decay_t<SEXP>>(realized_comp_sxp)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_ledgr_ledgr_cpp_spot_fifo_batch", (DL_FUNC) &_ledgr_ledgr_cpp_spot_fifo_batch, 18},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_ledgr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
