# Generated by cpp11: do not edit by hand

ledgr_cpp_spot_fifo_batch <- function(run_id_sxp, fill_inst_idx_sxp, fill_instrument_id_sxp, fill_side_sxp, fill_qty_sxp, fill_price_sxp, fill_fee_sxp, fill_ts_utc_sxp, event_seq_start_sxp, positions_sxp, cash_sxp, lot_inst_idx_sxp, lot_qty_sxp, lot_price_sxp, cost_basis_by_inst_sxp, total_cost_basis_sxp, realized_pnl_sxp, realized_comp_sxp) {
  .Call(`_ledgr_ledgr_cpp_spot_fifo_batch`, run_id_sxp, fill_inst_idx_sxp, fill_instrument_id_sxp, fill_side_sxp, fill_qty_sxp, fill_price_sxp, fill_fee_sxp, fill_ts_utc_sxp, event_seq_start_sxp, positions_sxp, cash_sxp, lot_inst_idx_sxp, lot_qty_sxp, lot_price_sxp, cost_basis_by_inst_sxp, total_cost_basis_sxp, realized_pnl_sxp, realized_comp_sxp)
}
