#' Synthetic demo OHLCV bars
#'
#' A deterministic, offline OHLCV dataset for ledgr examples and documentation.
#' It contains 10 synthetic instruments with five years of business-day bars.
#' The data is generated by `data-raw/make_demo_bars.R` using
#' `ledgr_sim_bars()`.
#'
#' @format A tibble with 12,600 rows and 7 columns:
#' \describe{
#'   \item{ts_utc}{POSIXct UTC bar timestamp.}
#'   \item{instrument_id}{Synthetic instrument identifier.}
#'   \item{open, high, low, close}{Synthetic OHLC prices.}
#'   \item{volume}{Synthetic daily volume.}
#' }
#' @source Generated locally by `ledgr_sim_bars(n_instruments = 10, n_days = 252 * 5, seed = 1701)`.
"ledgr_demo_bars"

#' Composable point-in-time demo inputs
#'
#' A deterministic, offline teaching bundle whose bars and point-in-time facts
#' form one self-contained input unit. It covers five synthetic equity
#' instruments (`DEMO_01` through `DEMO_05`) over 2020-01-01 through
#' 2020-01-31 under the synthetic `DEMO_VENUE` venue and `demo_members`
#' universe scopes. The matching observations use New York session-close
#' timestamps and travel with the facts; the facts must not be attached to an
#' arbitrary slice of [ledgr_demo_bars].
#'
#' @format An ordinary named list with nine elements:
#' \describe{
#'   \item{bars}{Matching synthetic OHLCV observations.}
#'   \item{instruments}{Optional physical instrument-master rows.}
#'   \item{sessions}{Raw input for [ledgr_facts_sessions()].}
#'   \item{membership}{Raw complete-snapshot input for
#'     [ledgr_facts_membership_snapshots()].}
#'   \item{lifetime}{Raw input for [ledgr_facts_lifetime()].}
#'   \item{trading_status}{Raw input for [ledgr_facts_trading_status()].}
#'   \item{corporate_actions}{Raw input for
#'     [ledgr_facts_equity_corporate_actions()].}
#'   \item{recipe}{Scope IDs, price basis, knowledge modes, and exact
#'     constructor arguments for the five fact frames.}
#'   \item{cases}{A manifest locating the weekday venue closure, open-session
#'     observation gap, delisting, halt, and validated gross cash dividend.}
#' }
#' @source Generated locally by `data-raw/make_demo_pit_inputs.R` from
#'   `ledgr_sim_pit_inputs()` with seed 1702.
"ledgr_demo_pit_inputs"
