#' Synthetic demo OHLCV bars
#'
#' A deterministic, offline OHLCV dataset for ledgr examples and documentation.
#' It contains 10 synthetic instruments with five years of business-day bars.
#' The data is generated by `data-raw/make_demo_bars.R` using
#' `ledgr_sim_bars()`.
#'
#' @format A data frame with 12,600 rows and 7 columns:
#' \describe{
#'   \item{ts_utc}{POSIXct UTC bar timestamp.}
#'   \item{instrument_id}{Synthetic instrument identifier.}
#'   \item{open, high, low, close}{Synthetic OHLC prices.}
#'   \item{volume}{Synthetic daily volume.}
#' }
#' @source Generated locally by `ledgr_sim_bars(n_instruments = 10, n_days = 252 * 5, seed = 1701)`.
"ledgr_demo_bars"
